### ISSUE TITLE
403 HTTP ERROR in downloading readingset.

### ISSUE THREAD

**Issue by BonbonKim** [alexa/Topical-Chat#11]
Thanks for very useful dataset.
This issue relates downloading readingset.
To download readingset, I've created API key and run the code build.py. I received an error message '**prawcore.exceptions.Forbidden: received 403 HTTP response**'.
 
 
![그림0](https://user-images.githubusercontent.com/75959020/124716250-d3d74900-df3e-11eb-9431-cc6b914cd976.GIF)
 
 
 
 
I excluded the data that the error occurs through exception processing. So, I downloaded dataset except for the data with ID below.(t3_2au72q) I would like to download this data.
 
 
![그림1](https://user-images.githubusercontent.com/75959020/124713556-a89f2a80-df3b-11eb-8072-409e69c4d7e7.GIF)
 
 
 
 
And can I ignore the warning message below?
 
 
![그림2](https://user-images.githubusercontent.com/75959020/124713716-da17f600-df3b-11eb-9670-642fd0641c56.GIF)

**Comment by HiCHanson** [comment]
I encountered the same problem as you, how did you solve it?

**Comment by hmolloy** [comment]
Hi there,
I'm also very appreciative of this dataset!  Unfortunately, I ran into the same 403 HTTP Response error when I was trying to build the data: 

![image](https://user-images.githubusercontent.com/29762455/144506436-434553ef-8a96-4f2c-84de-fb8b18edf4e2.png)

Any recommendations on how to proceed?

Thanks in advance!

**Comment by g-karthik** [comment]
@bonbon-au-choco @HiCHanson @hmolloy Thanks for reporting this issue!

We think this is happening because one of the Reddit r/todayilearned fun facts was removed from Reddit's servers due to unknown reasons, specifically the one associated with the ID: `t3_2au72q`.

We've posted that fun fact to r/todayilearned afresh, and it now has the ID: `t3_r8dxya`.

Could you please replace the old ID with the new ID in `train.json`, `valid_freq.json` and `valid_rare.json` within the `reading_sets/pre-build/` directory? And then try re-running the code? We think that should resolve the problem, but please do verify and let us know if it does resolve the problem for you!

Thanks again!

**Comment by jshin49** [comment]
you also need to change the stuff in test_*.json

**Comment by bhedayat** [comment]
closing issue. Please let us know if the problem has not been resolved
