### ISSUE TITLE
What is meant by the metric "unigram F1 of model prediction with groundtruth response" as mentioned in your paper?

### ISSUE THREAD

**Issue by dishavarshney082** [alexa/Topical-Chat#4]

**Comment by g-karthik** [comment]
@geekygirl123 here's a public implementation of [that](https://github.com/facebookresearch/ParlAI/blob/master/parlai/core/metrics.py#L352) metric.

**Comment by dishavarshney082** [comment]
Thanks for the link. Also wanted to ask that in your paper you mentioned that you observed poor agreement for interesting (0.29) and continue conversation (0.27). Is that the reason you didn't mention its score in table 4. I mean if we get less agreement score should we not show those results?

**Comment by dishavarshney082** [comment]
Also, the agreement score is for which model?

**Comment by g-karthik** [comment]
@geekygirl123 IIRC the agreement was not computed at a model-level, it was computed at a parameter-level. Yes, we didn't report the aggregated metrics for those two parameters because of the poor agreement scores -- we hypothesized that the poor agreement was due to the parameters being a bit more vague/subjective than the others. There could be other reasons for poor agreement, of course.

**Comment by dishavarshney082** [comment]
The ParlAI F1-score code computes F1-score for one predicted sample against a set of candidate sentences. So, for the whole test set, we compute the F1-score of each utterance and then average it. Is this the algorithm followed by you too?
Also, the F1-score reported in the paper, is it the percentage value (multiplied by 100)?

**Comment by bhedayat** [comment]
Yes. We computed the F1-score between the predicted sample and the ground truth response and averaged it. And yes we multiplied it by 100

**Comment by dishavarshney082** [comment]
Thanks @bhedayat
