### ISSUE TITLE
Diversity scores

### ISSUE THREAD

**Issue by dishavarshney082** [alexa/Topical-Chat#5]
How are the diversity scores calculated?. The paper referred in the topical chat paper has not mentioned the formula or the steps to calculate it. Is this the implementation [https://github.com/neural-dialogue-metrics/Distinct-N](url) used?

**Comment by dishavarshney082** [comment]
Also, as seen in the results section, there is an increase in ppl when knowledge is used even though the F1-score increases. Is there any relation between ppl and F1-score. How should we address such metrics? 
![image](https://user-images.githubusercontent.com/57398409/88335256-a3f45d00-cd50-11ea-9627-45e6008412a5.png)

**Comment by bhedayat** [comment]
Hi @geekygirl123 thank you for your questions. So we did not use that implementation you linked. The diversity referenced in this paper is utterance level n-gram diversity where we find the unique number of n-grams divided by the total number of tokens in the generated sentence. Do that for every utterance and average it together.

As for your question on F1 and ppl. F1-score is a unigram based score and has no sense of order. We believe when we injected knowledge the response generated unigrams that had knowledge words but the order of the sentence is not captured which can explain the increase in perplexity. Note however that this is a model-specific observation. We’ve used GPT-2 style models since we published this paper and we do see a positive correlation between F1 and PPL there.

Hope that helps.
