### ISSUE TITLE
Problems in downloading the dataset

### ISSUE THREAD

**Issue by Imposingapple** [alexa/Topical-Chat#6]
Thanks for your great dataset!
I met some problem in downloading the dataset running your code 'python3 build.py  --reddit_client_id CLIENT_ID --reddit_client_secret CLIENT_SECRET --reddit_user_agent USER_AGENT'. I've created my API key and after I ran the above code, I received an error message which is shown below.
![error2](https://user-images.githubusercontent.com/39848377/91017677-25296300-e621-11ea-9464-0f5d52f258e6.png)

I use the default redirect api, my reddit name and also string 'localhost'  as --reddit_user_agent, and all of them came to the same error message, so I could not download the dataset. I don't know the reason for that. I'm looking forward to your reply!

Thank you!

**Comment by g-karthik** [comment]
@Imposingapple From the stack-trace, it looks like your API key was throttled by the Reddit servers. You might consider waiting for a while and re-running, or creating a new key. Keep me posted.

**Comment by Imposingapple** [comment]
Thank you!
I can download the dataset now. However, I met some warning after finish downloading the dataset. Do these warnings matter? Do I download the files successfully? I don't know what's the meaning of these warnings. 
Looking forward to your reply, thank you very much!
![Uploading waring.png…]()

**Comment by Imposingapple** [comment]
![waring](https://user-images.githubusercontent.com/39848377/91423016-8738d100-e88a-11ea-8297-4ec96f715051.png)

**Comment by g-karthik** [comment]
That warning suggests that there is some difference between your built reading set JSONs and the ones we built on our side when we released the dataset.

We've not had anyone report this before. But IMO, it's possible that some fun fact on Reddit was slightly updated by the original posters on that platform, causing your built files to be somewhat different from the ones we built.

Do you mind sharing your built reading set files on a Drive with me? I can take a look at the diff and confirm this hypothesis.

**Comment by Imposingapple** [comment]
Sure. I've uploaded my post-built files in google drive. Here's the link.
https://drive.google.com/drive/folders/1HiaOTF3S9o1moVwMn7slV75Qha9k15vZ?usp=sharing

Thanks for helping me in downloading the dataset. Looking forward to your reply!

**Comment by g-karthik** [comment]
@Imposingapple sorry for the delay! From your screenshot, it looks like the warning did not print for `test_freq` and `test_rare`? Or did you just kill the script after seeing the first 3 warnings?

I computed the file hashes for all 5 files from your Drive, and it did not match for all of them.

But I also did this:

```
with open("/path/to/your/file.json", "r") as f:
     a = json.load(f)
with open("/path/to/my/file.json", "r") as f:
     b = json.load(f)

assert(a == b)
```

and I did not get an assertion error for any of your files.

EDIT: I also created a fresh clone of this repo and tried to build the dataset again from scratch with my own API key. The hash check went fine, it didn't give me a warning for any file. From these observations, I think you may have gotten the warnings because of excess indentation/spaces in your files. Also I see you're using Windows and not Linux/Unix, which may be a reason too - I didn't test this code on Windows when we released the dataset and I do not have access to a Windows machine to run this test. However, I think you can ignore the warning because my above asserts were fine for your files.

**Comment by Imposingapple** [comment]
Thank you for replying! I just load three of the files for convenience(because downloading dataset in my lap is very slow), so there are only three warnings. Do you mean this problem is something related to the operate system (I use windows 10 for downloading). And the dataset I've download is correct, and I can use it safely?


Sincerely,
2020/9/10
















At 2020-09-09 09:28:30, "Karthik Gopalakrishnan" <notifications@github.com> wrote:

@Imposingapple sorry for the delay! From your screenshot, it looks like the warning did not print for test_freq and test_rare? Or did you just kill the script after seeing the first 3 warnings?

I computed the file hashes for all 5 files from your Drive, and it did not match for all of them.

But I also did this:

with open("/path/to/your/file.json", "r") as f:
     a = json.load(f)
with open("/path/to/my/file.json", "r") as f:
     b = json.load(f)

assert(a == b)


and I did not get an assertion error for any of your files.

**Comment by g-karthik** [comment]
@Imposingapple but if you just built 3 of the files, how come your Drive has all 5 train/valid/test JSONs?

But yeah, given the above observations, I suspect the issue might either be your operating system or your JSON indentations were off, causing the warnings to show up for you.

I think you can ignore them since my dict comparison check of your files with my local files was successful.

Hope this helps!

**Comment by Imposingapple** [comment]
Thank you very much! 


Apple
2020/9/14
















At 2020-09-12 04:54:51, "Karthik Gopalakrishnan" <notifications@github.com> wrote:

@Imposingapple but if you just built 3 of the files, how come your Drive has all 5 train/valid/test JSONs?

But yeah, given the above observations, I suspect the issue might either be your operating system or your JSON indentations were off, causing the warnings to show up for you.

I think you can ignore them since my dict comparison check of your files with my local files was successful.

Hope this helps!
