### ISSUE TITLE
Audios for the Actual dataset (TopicalChatASR)

### ISSUE THREAD

**Issue by mailong25** [alexa/Topical-Chat#8]
"From each of the original test sets, 40 uniquely representative dialogs were picked and English-speaking human subjects of various ethnicities were asked to verbally read the dialogs with their own audio setup and record their audio, resulting in phonetically rich test sets."

Is there any plan to release the speech version of this dataset?

Thanks

**Comment by g-karthik** [comment]
@mailong25 Thanks a lot for the interest in our work!

The audio itself wasn't collected with the intention of being publicly released, since our [paper](https://arxiv.org/abs/2008.07683) was focused on performing a first-of-its-kind **speech**-based empirical benchmarking of **text**-based end-to-end open-domain dialogue models.

The ASR transcripts of the collected audio are available for reproducibility [here](https://github.com/alexa/Topical-Chat/tree/master/TopicalChatASR/actual). You could use them as test sets to report speech-robustness performance for your own text-based open-domain dialogue models in your future publications. Hope this helps!
